config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :employees
  resources :customers 
  resources :appointments
  

  root to: 'home#index'
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, Employee
      can :manage, User
      can :manage, Customer 
      can :manage, Appointment
    elsif user.accountant?
      can :manage, Customer 
      can :manage, Appointment
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  include Visible
  belongs_to :employee
  
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :employees, through: :appointments
end

app/models/employee.rb
class Employee < ApplicationRecord
    include Visible

    has_many :attendances, dependent: :destroy
    has_many :appointments, dependent: :destroy
    has_many :customers, through: :appointments
    # validates :name, presence: true
    # validates :email, presence: true
    # validates :phone, presence: true
    # validates :emptype, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  
  
  def admin?
    usertype=='admin'
  end
  
  def accountant?
    usertype == 'accountant'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, 
  if: :devise_controller?
  def configure_permitted_parameters              
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :email, :password, :password_confirmation,   :current_password)} 
  end

  # load_and_authorize_resource
  include Pagy::Backend
  rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, :alert => exception.message
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # before_action :authenticate_user!
  load_and_authorize_resource
    def index
      # @appointments = Appointment.all
      @pagy, @appointments = pagy(Appointment.all(), items: 10)

    end
  
    def new
      @appointment = Appointment.new
    end
  
    def create
      @appointment = Appointment.new(appointment_params)
      if @appointment.save
        redirect_to appointments_path, notice: 'Appointment created successfully.'
      else
        render :new
      end
    end
  
    def show
      @appointment = Appointment.find(params[:id])
    end
  
    def destroy
      @appointment = Appointment.find(params[:id])
      @appointment.destroy

      redirect_to appointments_path, status: :see_other
    end
  
    private
  
    def appointment_params
      params.require(:appointment).permit(:customer_id, :employee_id, :date)
    end
  end
  

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @attendances = Attendance.all
  end

  def new
    @attendance = Attendance.new
  end
  def create 
    @employee = Employee.find(params[:employee_id])
    @attendance = @employee.attendances.new(attendance_params)
    if @attendance.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @attendance = Attendance.find(params[:id])
  end

  def edit
    @attendance = Attendance.find(params[:id])
  end

  def update
    @attendance = Attendance.find(params[:id])

    if @attendance.update(attendance_params)
      redirect_to @attendance
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy
    redirect_to root_path, status: :see_other
  end

  private 
  def attendance_params 
    params.require(:attendance).permit(:date, :status, :remarks, :emptype, :employee_id)
  end

end

app/controllers/concerns/visible.rb
module Visible
 extend ActiveSupport::Concern 
 VALID_EMPTYPES = ['barbar','accountant', 'admin']
 ATTENDANCE_STATUS = ["Present", "Leave"]

 included do
    validates :emptype, inclusion: {in: VALID_EMPTYPES}
    # validates :status, inclusion: {in: ATTENDANCE_STATUS}
end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    # before_action :authenticate_user!
    load_and_authorize_resource
    def index 
        # @customers = Customer.all
        @pagy, @customers = pagy(Customer.all(), items: 10)

    end
    def new
        @customer = Customer.new
    end
    def create 
        @customer = Customer.new(customer_params)

        if @customer.save
            redirect_to customers_path
        else
            render :new 
        end
    end

    def destroy
        @customer = Customer.find(params[:id])
        @customer.destroy
    
        redirect_to customers_path, status: :see_other
    end

    private 
    def customer_params
        params.require(:customer).permit(:name, :email, :phone)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # before_action :authenticate_user!
  load_and_authorize_resource
  def index
    # @employees = Employee.all
    @pagy, @employees = pagy(Employee.all(), items: 10)

  end
  
  def new 
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(emp_params)

    if @employee.save 
      redirect_to employees_path
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit 
    @employee = Employee.find(params[:id])
  end


  def update
    @employee = Employee.find(params[:id])

    if @employee.update(emp_params)
      redirect_to employees_path
    else
      render :edit, status: :unprocessable_entity
    end

  end

  def destroy 
    @employee = Employee.find(params[:id])
    @employee.destroy

    redirect_to employees_path, status: :see_other
  end

  private 
  def emp_params
    params.require(:employee).permit(:name, :email, :emptype, :phone)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/_form.html.erb
<section class='h-100 h-custom' style="background-color: #8fc4b7">
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-8 col-xl-6">
        <div class="card rounded-3">
        <div class="card-body p-4 p-md-5">
          <%= form_with model: @appointment do |form| %>
            <% if @appointment.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

                <ul>
                  <% @appointment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field mb-3">
              <%= form.label :customer_id %>
              <%= form.collection_select :customer_id, Customer.all, :id, :name, :class=>"select form-control" %>
            </div>

            <div class="field mb-3">
              <%= form.label :employee_id %>
              <%= form.collection_select :employee_id, Employee.all.where(emptype:'barbar'), :id, :name %>
            </div>

            <div class="field mb-3">
              <%= form.label :date %>
              <%= form.datetime_local_field :date %>
            </div>

            <div class="actions">
              <%= form.submit %>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
</div>
</section>

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<%= link_to 'New Appointment', new_appointment_path, :class=>"btn btn-info" %>

<table class='table table-striped'>
  <tr>
    <th>Customer</th>
    <th>Staff</th>
    <th>Appointment Time</th>
    <th>Actions</th>
  </tr>
  <% @appointments.each do |appointment| %>
    <tr>
      <td><%= appointment.customer.name %></td>
      <td><%= appointment.employee.name %></td>
      <td><%= appointment.date %></td>
      <td>
        <%= link_to 'Show', appointment , :class=>"btn btn-info" %>
        <%= link_to 'Edit', edit_appointment_path(appointment) , :class=>"btn btn-primary" %>
        <%= link_to 'Delete', appointment_path(appointment), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
        }, :class=>"btn btn-danger" %>
      </td>
    </tr>
  <% end
  %>
</table>
 <%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

app/views/attendances/_form.html.erb
<%= form_with model: attendance do |form| %>
  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :employee %><br>
    <%= form.select(:employee_id, Employee.all.collect { |e| [e.name, e.id] }, {:include_blank => true, :selected => form.object.employee_id}) %>
<br>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::ATTENDANCE_STATUS %><br>
  </div>
  <div>
    <%= form.label :remarks %><br>
    <%= form.text_field :remarks %><br>
    
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>
<%= link_to "Mark Attendance", new_attendance_path %><hr>

<table class="table table-striped">
  <tr>
    <th>Date </th>             
    <th>Employee </th>                      
    <th>Status </th>                     
    <th>Edit </th>
    <th>Delete </th>
  </tr>
 <% @attendances.each do |attendance| %>
  <tr>
    <td><%= attendance.date%></td>         
    <td><%=attendance.employee %></td>   
    <td><%=attendance.status %></td>   
    <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>     
    <td><%= link_to 'Delete', attendance_path(attendance), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>  
    

  </tr>
  <% end %>
 </table>

app/views/attendances/new.html.erb
<h1>Attendances#new</h1>
<p>Find me in app/views/attendances/new.html.erb</p>

<h1>Mark Attendacne</h1>
<%= render 'form', attendance: @attendance%>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/customers/_form.html.erb
<%= form_with model: @customer do |form| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.collection_select :employee_id, Employee.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_local_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/index.html.erb
<h1>Customers</h1>

<%= link_to 'New Customer', new_customer_path, :class=>"btn btn-info" %>

<table class='table table-striped'>
  <tr>
    <th>Customer</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Actions</th>
  </tr>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.email %></td>
      <td><%= customer.phone %></td>
      <td>
        <%= link_to 'Show', customer, :class=>"btn btn-info" %>
        <%= link_to 'Edit', edit_customer_path(customer), :class=>"btn btn-primary" %>
        <%= link_to 'Delete', customer_path(customer), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
        }, :class=>"btn btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>
 <%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/customers/new.html.erb
<h1>Add New Customer</h2>

<%= form_with model: @customer do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %><br>
    
  </div>
  <div>
    <%= form.label :phone %><br>
    <%= form.number_field :phone %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/_form.html.erb
<%= form_with model: employee do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %><br>
    
  </div>
  <div>
    <%= form.label :phone %><br>
    <%= form.text_field :phone %><br>
    
  </div>
  <div>
    <%= form.label :emptype %><br>
    <%= form.select :emptype, Visible::VALID_EMPTYPES %><br>
    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<h1>Employees#update</h1>
<%= render 'form', employee: @employee %>
<%= link_to 'Employee', employee_path(@employee)%>
<%= link_to 'Show Employees', employees_path()%>

app/views/employees/index.html.erb
<h1>Employees List</h1>
<%= link_to 'Add Employee', new_employee_path, :class=>"btn btn-info" %>
<table class="table table-striped">
  <tr>
    <th>Name </th>             
    <th>Email </th>                      
    <th>Phone </th>
    <th>Employee Type </th>                      
    <th>Actions</th>
  </tr>
 <% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name%></td>         
    <td><%=employee.email %></td>   
    <td><%=employee.phone %></td>   
    <td><%=employee.emptype %></td>  
    <td><%= link_to 'Edit', edit_employee_path(employee), :class=>"btn btn-info" %><%= link_to 'Delete', employee_path(employee), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
    }, :class=>"btn btn-danger" %></td>  
    

  </tr>
  <% end %>
 </table>
 <%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/employees/new.html.erb
<h1>New employee</h1>
<%= render 'form', employee: @employee%>

app/views/employees/show.html.erb
<h1>Employees#show</h1>
    <p>
      <%= @employee.name %>
    </p>
    <p>
      <%= @employee.email %>
    </p>
    <p>
      <%= @employee.phone %>
    </p>
    <p>
      <%= @employee.emptype %>
    </p>
<ul>
    <li>
      <%= link_to "Edit", edit_employee_path(@employee) %>
    </li>
    <li><%= link_to "Destroy", employee_path(@employee), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>
<%= link_to 'Show Employees', employees_path()%>

app/views/home/index.html.erb
<% if current_user %>
    <% if current_user.usertype? %>
    <h1>Welcome to <%= current_user.usertype %> dashboard</h1>
    <% else %>
        <h3>You are guest user. Please refer to admin for rights. </h3>
    <% end %>
<% else %>
    <% controller.redirect_to new_user_session_path %>
<% end %>

app/views/layouts/_admin_dashboard.html.erb
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <%= link_to "Brand Logo", root_path, :class=>"navbar-brand ps-3" %>
            
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <% if current_user.avatar.attached? %>
                        <%= image_tag current_user.avatar, class:"rounded-circle", style:"height: 22px" %>
                    <% else %>
                    
                        <i class="fas fa-user fa-fw"></i>
                    <% end %>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><%= link_to "Edit Profile", edit_user_registration_path(@user) , class: "dropdown-item"%></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                    </ul>
                </li>
            </ul>
        </nav>
            <div id="layoutSidenav">          
                <% if current_user.usertype? %>
                <div id="layoutSidenav_nav">
                    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                        <div class="sb-sidenav-menu">
                            <div class="nav">
                                <div class="sb-sidenav-menu-heading">Core</div>
                                <a class="nav-link" href="/">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    <%= current_user.usertype.capitalize %> Dashboard
                                </a>
                                <div class="sb-sidenav-menu-heading">Interface</div>
                                <% if can? :manage, Employee %>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseEmployees" aria-expanded="false" aria-controls="collapseEmployees">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Manage Employees
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseEmployees" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <%= link_to "Add Employee", new_employee_path, :class=>"nav-link" %>
                                        <%= link_to "See Employees", employees_path, :class=>"nav-link" %>
                                    </nav>
                                </div>
                                <% end %>
                                <% if can? :manage, Customer %>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCustomer" aria-expanded="false" aria-controls="collapseCustomer">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Manage Customers
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseCustomer" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <%= link_to "Add Customer", new_customer_path, :class=>"nav-link" %>
                                        <%= link_to "See Customers", customers_path, :class=>"nav-link" %>
                                    </nav>
                                </div>
                                <% end %>
                                <% if can? :manage, Appointment %>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseAppointment" aria-expanded="false" aria-controls="collapseAppointment">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Manage Appointment
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseAppointment" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <%= link_to "Add Appointment", new_appointment_path, :class=>"nav-link" %>
                                        <%= link_to "See Appointments", appointments_path, :class=>"nav-link" %>
                                    </nav>
                                </div>
                                <% end %>
                            </div>
                        </div>
                        <div class="sb-sidenav-footer">
                            <div class="small">Logged in as:</div>
                            <%= current_user.usertype %> 
                        </div>
                    </nav>
                </div>
                <% end %>
                
                <div id="layoutSidenav_content">
                    <main>
                        <div class="container-fluid px-4">
                        <% if yield %>
                        <%= yield %>
                        <% else %>
                        <h1 class="mt-4">Static Navigation</h1>
                            <ol class="breadcrumb mb-4">
                                <li class="breadcrumb-item"><%= link_to "Dashboard Main", root_path %></li>
                                <li class="breadcrumb-item active">Static Navigation</li>
                            </ol>
                            <div class="card mb-4">
                                <div class="card-body">
                                    <p class="mb-0">
                                    <h1>Wellcome to Dashboard</h1>
                                        </p>
                                </div>
                            </div>
                        <% end %> 
                        </div>
                    </main>
                    <footer class="py-4 bg-light mt-auto">
                        <div class="container-fluid px-4">
                            <div class="d-flex align-items-center justify-content-between small">
                                <div class="text-muted">Copyright &copy; Twinspider.com 2023</div>
                                <div>
                                    <a href="#">Privacy Policy</a>
                                    &middot;
                                    <a href="#">Terms &amp; Conditions</a>
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
       

app/views/layouts/_navbar.html.erb
<%
=begin%>
 <%= render 'layouts/admin_dashboard2' %> 
<%
=end%>
<%
=begin%>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Brand", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       <%= link_to "Home", root_path, class: "nav-item nav-link" %>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link" %> 

          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %> 

        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 
<%
=end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingSystem</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%
=begin%>
 <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
<%
=end%>
  

    <%= javascript_importmap_tags %>

        <%= stylesheet_link_tag "styles.css" %>

        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
  </head>

  <body>

<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-lable="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-lable="Close"></button>
  </div>
<% end %>
  <div class="container-fluid">
  <% if current_user %>
    <%= render 'layouts/admin_dashboard' %>
  <% else %>
    <%= yield %>
  <% end %>
  </div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
  </body>
</html>